### ISSUE TITLE
2 tooltips at the same time even though wawla is disabled and config doesnt open

### ISSUE THREAD

**Issue by talha5758** [strubium/TheOneSmeagle#31]
![Image](https://github.com/user-attachments/assets/db68d9d2-0e36-4ca1-ab30-869489f96afc)

**Comment by strubium** [comment]
Fixed in 1.0.8

**Comment by talha5758** [comment]
it still shows both tooltips, should i delete the wawla config or something, or is there an option to disable the one in the middle

**Comment by talha5758** [comment]
oh wait, waila is enabled, sorry
